name: audio_book
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_styled_toast: ^2.2.1
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3
  firebase_auth: ^5.3.1
  firebase_crashlytics: ^4.1.3
  firebase_remote_config: ^5.1.3
  firebase_database: ^11.1.4
  firebase_storage: ^12.3.2
  audioplayers: ^6.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/font/
    - assets/images/
    - assets/images/banner/
    - assets/lotties/
